# Generated by Django 5.1.4 on 2024-12-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='threats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='WithDraw',
        ),
    ]
