# Generated by Django 5.1.4 on 2024-12-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_user_threats_delete_withdraw'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
