# Generated by Django 5.1.4 on 2025-01-06 14:04

import apps.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_profile_withdraw'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.models.CustomUser()),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
